CREATE SCHEMA IF NOT EXISTS PRODUCT;
CREATE TABLE PRODUCT.PRODUCT
(
    ID            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CREATED_DATE  timestamp(6),
    MODIFIED_DATE timestamp(6),
    COUNT         integer,
    DESCRIPTION   varchar(255),
    PRICE         numeric(38, 2),
    TITLE         varchar(255)
)